source 'https://rubygems.org'

gem 'json' 
gem 'nokogiri'
gem 'pry'
gem 'rake'
gem 'rdoc'
gem 'rest-client'
gem 'rspec', '3.2.0'
gem 'rspec-core', '3.2.3'
gem 'rspec-expectations', '3.2.1'
gem 'rspec-mocks', '3.2.1'
gem 'rspec-support', '3.2.2'
gem 'watir-webdriver'
gem 'launchy'
gem 'ripl' # for interactive testing